/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  // blogSidebar: [{ type: 'category', label: '微信小程序(0)', }]

}

module.exports = sidebars;
